CREATE TABLE `clinicalfirst_services`.`patient_registration` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PATIENT_ID` VARCHAR(200) NULL,
  `PATIENT_AGE` VARCHAR(10) NULL,
  `PATIENT_EXPERIANCE` INT(30) NULL,
  `PATIENT_GENDERl` VARCHAR(10) NULL,
  `PATIENT_LICENSE_NUMBERl` VARCHAR(100) NULL,
  `FLAT_NO` VARCHAR(50) NULL,
  `STREET_NAME` VARCHAR(45) NULL,
  `CITY_NAME` VARCHAR(45) NULL,
  `STATE_NAME` VARCHAR(45) NULL,
  `COUNTRY_NAME` VARCHAR(45) NULL,
  `ZIP_CODE` VARCHAR(50) NULL,
  `PATIENT_APPROVED` VARCHAR(45) NULL,
  `PATIENT_IP` VARCHAR(50) NULL,
  `PATIENT_DATE_REGISTERED` DATETIME NULL,
  `PATIENT_DEVICE` VARCHAR(50) NULL,
  PRIMARY KEY (`ID`));

SELECT * FROM clinicalfirst_services.patient_registration;

desc patient_registration;

ALTER TABLE `clinicalfirst_services`.`patient_registration`
ADD COLUMN `image` BLOB NULL AFTER `PATIENT_DEVICE`;

ALTER TABLE patient_registration
RENAME COLUMN image TO image_1;

ALTER TABLE patient_registration
RENAME COLUMN image_1 TO image;

ALTER TABLE patient_registration
DROP COLUMN image;

CREATE TABLE `clinicalfirst_services`.`patient_sub_registration` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PATIENT_ID` VARCHAR(200) NULL,
  `PATIENT_SUB_ID` VARCHAR(200) NULL,
  `PATIENT_AGE` VARCHAR(10) NULL,
  `PATIENT_EXPERIANCE` INT(30) NULL,
  `PATIENT_GENDERl` VARCHAR(10) NULL,
  `PATIENT_LICENSE_NUMBERl` VARCHAR(100) NULL,
  `FLAT_NO` VARCHAR(50) NULL,
  `STREET_NAME` VARCHAR(45) NULL,
  `CITY_NAME` VARCHAR(45) NULL,
  `STATE_NAME` VARCHAR(45) NULL,
  `COUNTRY_NAME` VARCHAR(45) NULL,
  `ZIP_CODE` VARCHAR(50) NULL,
  `PATIENT_APPROVED` VARCHAR(45) NULL,
  `PATIENT_IP` VARCHAR(50) NULL,
  `PATIENT_DATE_REGISTERED` DATETIME NULL,
  `PATIENT_DEVICE` VARCHAR(50) NULL,
  PRIMARY KEY (`ID`));



